export default tags = [
    "natty or not",
    "coaching",
    "beginner",
    "intermediate",
    "advanced",
    "meal prep",
    "diet",
    "weight loss",
    "weight gain",
    "supplementation",
    "powerlifting",
    "weightlifting",
    "bodybuilding",
    "physique",
    "personal record",
    "posing",
    "program structuring",
    "hypertrophy",
    "calisthenics",
    "cardio",
    "endurance",
    "athletic performance",
    "agility",
    "mobility & stretching",
];